### ISSUE TITLE
Missing Files for Final Project Grading

### ISSUE THREAD

**Issue by Caealana** [jtitzer/musclehub#1]
Hi @jtitzer! If you would like your final Codecademy IDA project to be graded, you need to upload your .py code file and .pdf of your slides. Let me know if you have any questions!

Thanks,
Caelana

**Comment by jtitzer** [comment]
Caelana,

My project was already graded in the  intro-data-capstone-musclehub
<https://github.com/jtitzer/intro-data-capstone-musclehub> repository*. *
I had trouble with the git function.

sorry for the confusion.

Jacob

**Comment by Caealana** [comment]
@jtitzer OK, thanks! Sorry for the confusion.
